---
- name: create instances directories
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - "{{ base_dir }}/instances"
    - "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}"
    - "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/volumes"
    - "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/volumes/logs"
    - "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/volumes/server"
    - "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/volumes/db"
    - "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/volumes/media"
    
- name: create docker-compose file
  template:
    src: docker-compose.yml.template
    dest: "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/docker-compose.yml"

- name: retrieve sources
  git:
    clone: yes
    repo: "{{ repo }}"
    dest: "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/src"

- name: retrieve wsgi dockerfile
  template:
    src: Dockerfile-wsgi.template
    dest: "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/Dockerfile-wsgi"

- name: retrieve nginx dockerfile
  template:
    src: Dockerfile-nginx.template
    dest: "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/Dockerfile-nginx"

- name: render nginx instance proxy
  template:
    src: nginx.conf.template
    dest: "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/volumes/server/{{ domain }}.conf"

- name: render nginx.conf for project proxy
  template:
    src: domain_nginx.conf.template
    dest: "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/{{ domain }}.conf"
  
- name: add deploy_settings.py
  template:
    src: deploy_settings.py.template
    dest: "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/src/{{ src_subdir }}/{{ project_name }}/deploy_settings.py"

- name: add deploy_wsgi.py
  template:
    src: deploy_wsgi.py.template
    dest: "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/src/{{ src_subdir }}/{{ project_name }}/deploy_wsgi.py"

- name: render uWSGI.ini
  template:
    src: uWSGI.ini.template
    dest: "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/uWSGI.ini"
      
- name: deploy
  shell:
    docker-compose up --build -d
  args:
    chdir: "{{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}"

- name: add nginx conf to proxy sites
  shell: "cp {{ base_dir }}/instances/{{ project_name }}_{{ instance_name }}/{{ domain }}.conf {{ base_dir }}/{{ project_name }}_proxy/vhosts/{{ domain }}.conf"

- name: restart proxy
  shell: "docker-compose up --build -d"
  args:
    chdir: "{{ base_dir }}/{{ project_name }}_proxy"
