FROM debian

RUN apt-get update -y && apt-get install -y libopencv-dev libmicrohttpd-dev libjsoncpp-dev cmake git &&  git clone  https://github.com/Visu4link/pastec.git && mkdir /pastec/build
WORKDIR /pastec/build
ADD http://pastec.io/files/visualWordsORB.tar.gz ./
RUN cmake ../ && make
EXPOSE 4212

CMD ["./pastec", "visualWordsORB.dat"]
