FROM nginx

RUN groupadd -g {{ user_gid.stdout }} {{ deployer_user }}
RUN useradd -u {{ user_uid.stdout }} -g {{ deployer_user }} {{ deployer_user }}
RUN  sed -i '/user  nginx;/c\user  {{ deployer_user }} {{ deployer_user }};' /etc/nginx/nginx.conf
{% if not src_as_vol %}
ADD volumes/server /etc/nginx/conf.d
{% endif %}

VOLUME /var/log/proxy_logs
VOLUME /tmp
